-- Migration V8: Investments, Permissions, and Ledger Updates

-- 1. Update Invoices Table
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by_name TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by_email TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES auth.users(id);

-- 2. Update Finance Entries Table (Deletion Logic)
ALTER TABLE finance_entries ADD COLUMN IF NOT EXISTS deletion_requested BOOLEAN DEFAULT FALSE;
ALTER TABLE finance_entries ADD COLUMN IF NOT EXISTS deletion_requested_by UUID REFERENCES auth.users(id);
-- Ensure created_by exists if not already
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_entries' AND column_name = 'created_by') THEN
        ALTER TABLE finance_entries ADD COLUMN created_by UUID REFERENCES auth.users(id);
    END IF;
END $$;

-- 3. Create Investments Table
CREATE TABLE IF NOT EXISTS investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    type TEXT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    date_bought DATE DEFAULT CURRENT_DATE,
    purpose TEXT,
    created_by UUID REFERENCES auth.users(id),
    created_by_name TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS on Investments
ALTER TABLE investments ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for Investments
-- Admin: Full Access
DROP POLICY IF EXISTS "Admins can do everything on investments" ON investments;
CREATE POLICY "Admins can do everything on investments" ON investments
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- Employees: View All, Create (Default Pending)
DROP POLICY IF EXISTS "Employees can view investments" ON investments;
CREATE POLICY "Employees can view investments" ON investments
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Employees can create investments" ON investments;
CREATE POLICY "Employees can create investments" ON investments
    FOR INSERT
    WITH CHECK (auth.uid() = created_by);

-- 6. Shared Client Visibility (Admin & Employee)
-- Drop old policies to valid conflicts
DROP POLICY IF EXISTS "Clients enable select for authenticated users" ON clients;
DROP POLICY IF EXISTS "Clients enable insert for authenticated users" ON clients;
DROP POLICY IF EXISTS "Clients are viewable by everyone" ON clients;

-- Allow everyone to read clients
DROP POLICY IF EXISTS "Everyone can view clients" ON clients;
CREATE POLICY "Everyone can view clients" ON clients
    FOR SELECT
    USING (true);

-- Allow authenticated users to insert clients
DROP POLICY IF EXISTS "Authenticated users can insert clients" ON clients;
CREATE POLICY "Authenticated users can insert clients" ON clients
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Allow admins to update/delete
DROP POLICY IF EXISTS "Admins can update clients" ON clients;
CREATE POLICY "Admins can update clients" ON clients
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

DROP POLICY IF EXISTS "Admins can delete clients" ON clients;
CREATE POLICY "Admins can delete clients" ON clients
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 7. Update Employees Table to be Publicly Readable for Email Checks (Required for Forgot Password Logic)
-- Strictly limiting to ID and Email for security
DROP POLICY IF EXISTS "Public can check employee existence" ON employees;
CREATE POLICY "Public can check employee existence" ON employees
    FOR SELECT
    USING (true);

-- 8. Fix RLS for Finance Entries (Deletion Request Logic)
DROP POLICY IF EXISTS "Employees can request deletion" ON finance_entries;
CREATE POLICY "Employees can request deletion" ON finance_entries
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
